Repository Songyee-Challenge/Server, pull requests merged in 2023-11, with the labels that each got.

#2 [Feat] 프로젝트 초기 설정 (#1)
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/likelion/songyeechallenge/SongyeeChallengeApplication.java
  src/main/resources/application.properties
  src/test/java/com/likelion/songyeechallenge/SongyeeChallengeApplicationTests.java
Labels: feature

#4 [Chore] dependency 추가 (#1)
  build.gradle
Labels: enhancement

#6 [Feat] 챌린지 개설하기 (#5)
  build.gradle
  src/main/java/com/likelion/songyeechallenge/controller/ChallengeController.java
  src/main/java/com/likelion/songyeechallenge/domain/challenge/Challenge.java
  src/main/java/com/likelion/songyeechallenge/domain/challenge/ChallengeRepository.java
  src/main/java/com/likelion/songyeechallenge/domain/challenges/Challenges.java
  src/main/java/com/likelion/songyeechallenge/domain/mission/Mission.java
  src/main/java/com/likelion/songyeechallenge/domain/mission/MissionRepository.java
  src/main/java/com/likelion/songyeechallenge/domain/missons/Missons.java
  src/main/java/com/likelion/songyeechallenge/domain/picture/Picture.java
  src/main/java/com/likelion/songyeechallenge/domain/picture/PictureRepository.java
  src/main/java/com/likelion/songyeechallenge/domain/pictures/Pictures.java
  src/main/java/com/likelion/songyeechallenge/domain/review/Review.java
  src/main/java/com/likelion/songyeechallenge/domain/user/User.java
  src/main/java/com/likelion/songyeechallenge/domain/user/UserRepository.java
  src/main/java/com/likelion/songyeechallenge/service/ChallengeService.java
  src/main/java/com/likelion/songyeechallenge/service/MissionService.java
  src/main/java/com/likelion/songyeechallenge/service/PictureService.java
  src/main/java/com/likelion/songyeechallenge/web/dto/ChallengeSaveRequestDto.java
  src/main/java/com/likelion/songyeechallenge/web/dto/MissionSaveRequestDto.java
  src/main/java/com/likelion/songyeechallenge/web/dto/PictureResponseDto.java
  src/main/resources/static/images/00ff3dfd-8943-4315-9b45-9b9b1c07e237.png
  src/main/resources/static/images/8b5363c2-31c5-44e2-afd4-1c7031a15787.png
Labels: feature

#8 [Del] 로컬에 저장된 이미지 삭제 (#7)
  src/main/resources/static/images/00ff3dfd-8943-4315-9b45-9b9b1c07e237.png
  src/main/resources/static/images/8b5363c2-31c5-44e2-afd4-1c7031a15787.png
Labels: documentation

#10 [Feat] 진행 상황 별 챌린지 조회 (#9)
  src/main/java/com/likelion/songyeechallenge/controller/ChallengeController.java
  src/main/java/com/likelion/songyeechallenge/domain/challenge/ChallengeRepository.java
  src/main/java/com/likelion/songyeechallenge/service/ChallengeService.java
  src/main/java/com/likelion/songyeechallenge/service/PictureService.java
  src/main/java/com/likelion/songyeechallenge/web/dto/ChallengeListResponseDto.java
Labels: feature

#14 [Feat] 메인페이지 구현 (#13)
  src/main/java/com/likelion/songyeechallenge/controller/MainPageController.java
  src/main/java/com/likelion/songyeechallenge/domain/challenge/ChallengeRepository.java
  src/main/java/com/likelion/songyeechallenge/service/MainPageService.java
  src/main/java/com/likelion/songyeechallenge/web/dto/MainPageResponseDto.java
Labels: feature

#17 [Feat] 챌린지 검색 (#16)
  src/main/java/com/likelion/songyeechallenge/controller/ChallengeController.java
  src/main/java/com/likelion/songyeechallenge/domain/challenge/ChallengeRepository.java
  src/main/java/com/likelion/songyeechallenge/service/ChallengeService.java
Labels: feature

#21 [feat] 로그인 및 회원가입 구현 (#20)
  build.gradle
  src/main/java/com/likelion/songyeechallenge/config/WebSecurityConfig.java
  src/main/java/com/likelion/songyeechallenge/controller/AdminController.java
  src/main/java/com/likelion/songyeechallenge/controller/HomeController.java
  src/main/java/com/likelion/songyeechallenge/controller/LoginController.java
  src/main/java/com/likelion/songyeechallenge/controller/UserController.java
  src/main/java/com/likelion/songyeechallenge/domain/user/User.java
  src/main/java/com/likelion/songyeechallenge/service/UserService.java
  src/main/java/com/likelion/songyeechallenge/service/UserServiceImpl.java
  src/main/java/com/likelion/songyeechallenge/user_dto/UserFormDto.java
  src/main/resources/templates/admin.html
  src/main/resources/templates/home.html
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
  src/main/resources/templates/signup.html
Labels: feature

#24 챌린지 리뷰작성 (#23)
  src/main/java/com/likelion/songyeechallenge/controller/ReviewController.java
  src/main/java/com/likelion/songyeechallenge/domain/review/Review.java
  src/main/java/com/likelion/songyeechallenge/domain/review/ReviewRepository.java
  src/main/java/com/likelion/songyeechallenge/service/ChallengeService.java
  src/main/java/com/likelion/songyeechallenge/service/ReviewService.java
  src/main/java/com/likelion/songyeechallenge/web/dto/ReviewChallengeDto.java
  src/main/java/com/likelion/songyeechallenge/web/dto/ReviewSaveRequestDto.java
  src/main/resources/static/images/fcc3ded5-fe62-4ca6-b934-5e9e882bed9c.png
Labels: feature

#26 [Feat] 리뷰 전체 조회 (#25)
  build.gradle
  src/main/java/com/likelion/songyeechallenge/SongyeeChallengeApplication.java
  src/main/java/com/likelion/songyeechallenge/config/dto/SecurityUtil.java
  src/main/java/com/likelion/songyeechallenge/controller/ReviewController.java
  src/main/java/com/likelion/songyeechallenge/domain/BaseTimeEntity.java
  src/main/java/com/likelion/songyeechallenge/domain/challenge/Challenge.java
  src/main/java/com/likelion/songyeechallenge/domain/challenge/ChallengeRepository.java
  src/main/java/com/likelion/songyeechallenge/domain/likes/Like.java
  src/main/java/com/likelion/songyeechallenge/domain/likes/LikeRepository.java
  src/main/java/com/likelion/songyeechallenge/domain/review/Review.java
  src/main/java/com/likelion/songyeechallenge/domain/review/ReviewRepository.java
  src/main/java/com/likelion/songyeechallenge/domain/user/User.java
  src/main/java/com/likelion/songyeechallenge/service/ChallengeService.java
  src/main/java/com/likelion/songyeechallenge/service/ReviewService.java
  src/main/java/com/likelion/songyeechallenge/web/dto/ChallengeSaveRequestDto.java
  src/main/java/com/likelion/songyeechallenge/web/dto/ReviewListResponseDto.java
  src/main/java/com/likelion/songyeechallenge/web/dto/ReviewSaveRequestDto.java
  src/main/resources/static/images/182c4218-9d1e-40ed-8bcd-79bcf49ef6a3.png
Labels: feature

#28 [Feat] JWT 구현 및 관련 코드 수정 (#27)
  .gitignore
  build.gradle
  src/main/java/com/likelion/songyeechallenge/config/CustomUserDetails.java
  src/main/java/com/likelion/songyeechallenge/config/CustomUserDetailsService.java
  src/main/java/com/likelion/songyeechallenge/config/JwtTokenFilter.java
  src/main/java/com/likelion/songyeechallenge/config/JwtTokenProvider.java
  src/main/java/com/likelion/songyeechallenge/config/WebSecurityConfig.java
  src/main/java/com/likelion/songyeechallenge/config/dto/AuthResponseDto.java
  src/main/java/com/likelion/songyeechallenge/config/dto/LoginRequestDto.java
  src/main/java/com/likelion/songyeechallenge/config/dto/SecurityUtil.java
  src/main/java/com/likelion/songyeechallenge/config/dto/SignupRequestDto.java
  src/main/java/com/likelion/songyeechallenge/controller/ChallengeController.java
  src/main/java/com/likelion/songyeechallenge/controller/HomeController.java
  src/main/java/com/likelion/songyeechallenge/controller/LoginController.java
  src/main/java/com/likelion/songyeechallenge/controller/ReviewController.java
  src/main/java/com/likelion/songyeechallenge/controller/UserController.java
  src/main/java/com/likelion/songyeechallenge/domain/auth/Auth.java
  src/main/java/com/likelion/songyeechallenge/domain/auth/AuthRepository.java
  src/main/java/com/likelion/songyeechallenge/domain/challenge/Challenge.java
  src/main/java/com/likelion/songyeechallenge/domain/challenge/ChallengeRepository.java
  src/main/java/com/likelion/songyeechallenge/domain/likes/Like.java
  src/main/java/com/likelion/songyeechallenge/domain/likes/LikeRepository.java
  src/main/java/com/likelion/songyeechallenge/domain/review/Review.java
  src/main/java/com/likelion/songyeechallenge/domain/user/Role.java
  src/main/java/com/likelion/songyeechallenge/domain/user/User.java
  src/main/java/com/likelion/songyeechallenge/domain/user/UserRepository.java
  src/main/java/com/likelion/songyeechallenge/service/ChallengeService.java
  src/main/java/com/likelion/songyeechallenge/service/ReviewService.java
  src/main/java/com/likelion/songyeechallenge/service/UserService.java
  src/main/java/com/likelion/songyeechallenge/service/UserServiceImpl.java
  src/main/java/com/likelion/songyeechallenge/user_dto/UserFormDto.java
  src/main/java/com/likelion/songyeechallenge/web/dto/ChallengeSaveRequestDto.java
  src/main/java/com/likelion/songyeechallenge/web/dto/ReviewSaveRequestDto.java
  src/main/resources/application.properties
  src/main/resources/static/images/182c4218-9d1e-40ed-8bcd-79bcf49ef6a3.png
  src/main/resources/static/images/fcc3ded5-fe62-4ca6-b934-5e9e882bed9c.png
Labels: bug, feature, enhancement

#37 [Chore] 나의 챌린지 수정 및 병합과정 중 생긴 오류 해결 (#33)
  src/main/java/com/likelion/songyeechallenge/config/dto/ChallengeListResponseDto.java
  src/main/java/com/likelion/songyeechallenge/config/dto/MyChallengeListResponseDto.java
  src/main/java/com/likelion/songyeechallenge/config/dto/MyMissionResponseDto.java
  src/main/java/com/likelion/songyeechallenge/controller/ChallengeController.java
  src/main/java/com/likelion/songyeechallenge/controller/MainPageController.java
  src/main/java/com/likelion/songyeechallenge/controller/MyPageController.java
  src/main/java/com/likelion/songyeechallenge/domain/challenge/Challenge.java
  src/main/java/com/likelion/songyeechallenge/domain/challenge/ChallengeRepository.java
  src/main/java/com/likelion/songyeechallenge/service/ChallengeService.java
  src/main/java/com/likelion/songyeechallenge/service/MainPageService.java
  src/main/java/com/likelion/songyeechallenge/service/MyPageService.java
  src/main/java/com/likelion/songyeechallenge/web/dto/ChallengeListResponseDto.java
  src/main/java/com/likelion/songyeechallenge/web/dto/MyMissionResponseDto.java
  src/main/java/com/likelion/songyeechallenge/web/dto/PictureResponseDto.java
Labels: bug, enhancement

#39 Feature/#38 myreview
  src/main/java/com/likelion/songyeechallenge/controller/MyPageController.java
  src/main/java/com/likelion/songyeechallenge/domain/review/Review.java
  src/main/java/com/likelion/songyeechallenge/domain/review/ReviewRepository.java
  src/main/java/com/likelion/songyeechallenge/domain/user/User.java
  src/main/java/com/likelion/songyeechallenge/service/MyPageService.java
  src/main/java/com/likelion/songyeechallenge/service/ReviewService.java
  src/main/java/com/likelion/songyeechallenge/web/dto/MyReviewResponseDto.java
  src/main/java/com/likelion/songyeechallenge/web/dto/ReviewChallengeDto.java
  src/main/java/com/likelion/songyeechallenge/web/dto/ReviewSaveRequestDto.java
Labels: bug, enhancement

#44 [feat] 메일 인증번호 전송
  src/main/java/com/likelion/songyeechallenge/VO/MailVo.java
  src/main/java/com/likelion/songyeechallenge/config/WebSecurityConfig.java
  src/main/java/com/likelion/songyeechallenge/controller/HomeController.java
  src/main/java/com/likelion/songyeechallenge/controller/LoginController.java
  src/main/java/com/likelion/songyeechallenge/controller/MailController.java
  src/main/resources/application.properties
Labels: feature

#51 [Fix] Cors 에러 해결 (#50)
  src/main/java/com/likelion/songyeechallenge/config/WebSecurityConfig.java
Labels: bug

#58 [Fix] 사진 400 에러 해결 (#55)
  src/main/java/com/likelion/songyeechallenge/controller/PictureController.java
  src/main/java/com/likelion/songyeechallenge/web/dto/ChallengeDetailResponseDto.java
  src/main/java/com/likelion/songyeechallenge/web/dto/ChallengeListResponseDto.java
  src/main/java/com/likelion/songyeechallenge/web/dto/MainPageResponseDto.java
  src/main/resources/static/images/4fd20ada-8070-4577-ac19-6a96e857e3dd.png
Labels: bug

#72 Feature/#71 mission complete
  src/main/java/com/likelion/songyeechallenge/controller/MyPageController.java
  src/main/java/com/likelion/songyeechallenge/domain/mission/Mission.java
  src/main/java/com/likelion/songyeechallenge/domain/mission/MissionRepository.java
  src/main/java/com/likelion/songyeechallenge/domain/mission/MissionUser.java
  src/main/java/com/likelion/songyeechallenge/domain/review/Review.java
  src/main/java/com/likelion/songyeechallenge/domain/user/User.java
  src/main/java/com/likelion/songyeechallenge/domain/user/UserRepository.java
  src/main/java/com/likelion/songyeechallenge/domain/userMission/UserMission.java
  src/main/java/com/likelion/songyeechallenge/domain/userMission/UserMissionRepository.java
  src/main/java/com/likelion/songyeechallenge/service/ChallengeService.java
  src/main/java/com/likelion/songyeechallenge/service/MyPageService.java
  src/main/java/com/likelion/songyeechallenge/web/dto/MissionResponseDto.java
  src/main/java/com/likelion/songyeechallenge/web/dto/MyMissionCompleteDto.java
  src/main/java/com/likelion/songyeechallenge/web/dto/MyMissionResponseDto.java
Labels: bug, feature, enhancement

#86 Feature/#85 enchancement logic
  src/main/java/com/likelion/songyeechallenge/controller/MainPageController.java
  src/main/java/com/likelion/songyeechallenge/controller/MyPageController.java
  src/main/java/com/likelion/songyeechallenge/domain/challenge/ChallengeRepository.java
  src/main/java/com/likelion/songyeechallenge/service/MainPageService.java
  src/main/java/com/likelion/songyeechallenge/service/MyPageService.java
  src/main/java/com/likelion/songyeechallenge/web/dto/MainPageResponseDto.java
  src/main/java/com/likelion/songyeechallenge/web/dto/MyChallengeListResponseDto.java
Labels: enhancement

#89 [Chore] 사진 정보 추가 (#87)
  src/main/java/com/likelion/songyeechallenge/web/dto/MainPageResponseDto.java
Labels: enhancement

#91 Feature/#90 edit mission save way
  src/main/java/com/likelion/songyeechallenge/service/ChallengeService.java
  src/main/java/com/likelion/songyeechallenge/service/MissionService.java
Labels: enhancement
